name: ftp-deploy

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: js-weather-dashboard.atwebpages.com
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        log-level: minimal
        server-dir: /js-weather-dashboard.atwebpages.com/
        local-dir: src/
