name: ftp-deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: js-weather-dashboard.atwebpages.com
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        log-level: minimal
        server-dir: /js-weather-dashboard.atwebpages.com/
        local-dir: src/
